# AppVeyor CI configuration for Minishift
---
version: "{build}"

clone_folder: C:\gopath\src\github.com\minishift\minishift

environment:
  GOPATH: C:\gopath

platform:
- x64

install:
# Dump some info
- go version
- go env
# Install Glide and create a specific tmp path to avoid error with too long dir names
- ps: mkdir "$env:GOPATH\bin"
- ps: wget 'https://github.com/Masterminds/glide/releases/download/v0.12.3/glide-v0.12.3-windows-amd64.zip' -OutFile "$env:GOPATH\bin\glide-v0.12.3-windows-amd64.zip"
- ps: 7z.exe e "$env:GOPATH\bin\glide-v0.12.3-windows-amd64.zip" -o"$env:GOPATH\bin" glide.exe -r
- set PATH=%PATH%;%GOPATH%\bin
- mkdir c:\tmp
# Use Chocolatey to install make
- choco install make

build_script:
- make cross test fmtcheck

artifacts:
  - path: out\linux-amd64\minishift
    name: Linux minishift binary
  - path: out\darwin-amd64\minishift
    name: OS-X minishift binary
  - path: out\windows-amd64\minishift.exe
    name: Windows minishift binary
